import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import localFont from "next/font/local";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const carnivalee = localFont({
    src: "../public/fonts/carnivalee.ttf",
    display: "swap",
    variable: "--font-carnivalee",
});

const buffalo = localFont({
    src: "../public/fonts/buffalo.ttf",
    display: "swap",
    variable: "--font-buffalo",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${inter.variable}  ${carnivalee.variable} ${buffalo.variable} `}>
                <div className='min-h-screen flex flex-col w-full bg-white'>
                    <Navbar />
                    <main className='flex-1 flex flex-col  w-full  '>{children}</main>
                </div>
            </body>
        </html>
    );
}
